//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebParaDBP.ServiciosLaboratorio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosLaboratorio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCiudades", ReplyAction="http://tempuri.org/IService1/getCiudadesResponse")]
        string[] getCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCiudades", ReplyAction="http://tempuri.org/IService1/getCiudadesResponse")]
        System.Threading.Tasks.Task<string[]> getCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarInformacion", ReplyAction="http://tempuri.org/IService1/GuardarInformacionResponse")]
        void GuardarInformacion(string nombre, string apellidos, string sexo, string correo, string direccion, string ciudad, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarInformacion", ReplyAction="http://tempuri.org/IService1/GuardarInformacionResponse")]
        System.Threading.Tasks.Task GuardarInformacionAsync(string nombre, string apellidos, string sexo, string correo, string direccion, string ciudad, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCiudades_SQL", ReplyAction="http://tempuri.org/IService1/GetCiudades_SQLResponse")]
        string[] GetCiudades_SQL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCiudades_SQL", ReplyAction="http://tempuri.org/IService1/GetCiudades_SQLResponse")]
        System.Threading.Tasks.Task<string[]> GetCiudades_SQLAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AplicacionWebParaDBP.ServiciosLaboratorio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AplicacionWebParaDBP.ServiciosLaboratorio.IService1>, AplicacionWebParaDBP.ServiciosLaboratorio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getCiudades() {
            return base.Channel.getCiudades();
        }
        
        public System.Threading.Tasks.Task<string[]> getCiudadesAsync() {
            return base.Channel.getCiudadesAsync();
        }
        
        public void GuardarInformacion(string nombre, string apellidos, string sexo, string correo, string direccion, string ciudad, string descripcion) {
            base.Channel.GuardarInformacion(nombre, apellidos, sexo, correo, direccion, ciudad, descripcion);
        }
        
        public System.Threading.Tasks.Task GuardarInformacionAsync(string nombre, string apellidos, string sexo, string correo, string direccion, string ciudad, string descripcion) {
            return base.Channel.GuardarInformacionAsync(nombre, apellidos, sexo, correo, direccion, ciudad, descripcion);
        }
        
        public string[] GetCiudades_SQL() {
            return base.Channel.GetCiudades_SQL();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCiudades_SQLAsync() {
            return base.Channel.GetCiudades_SQLAsync();
        }
    }
}
